export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';

//USER ACTIONS

export const CHECK_LOGGED_IN_STATUS = 'CHECK_LOGGED_IN_STATUS';
export const LOG_IN_USER = 'LOG_IN_USER';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const UPDATE_USER_STATUS = 'UPDATE_USER_STATUS'
export const PENDING_USER_LOGIN = 'PENDING_USER_LOGIN'
export const ERROR_LOGGING_IN = 'ERROR_LOGGING_IN'
export const REGISTER_USER = 'REGISTER_USER'
export const REGISTERING_USER = 'REGISTERING_USER'
export const ERROR_REGISTERING_USER = 'ERROR_REGISTERING_USER'
export const GET_CURRENT_USER = 'GET_CURRENT_USER'
export const SUCCESSFUL_GET_USER = 'SUCCESSFUL_GET_USER'
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA'



//full screen dialog

export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';



//color picker 

export const PICK_COLOR_1 = 'PICK_COLOR_1';
export const PICK_COLOR_2 = 'PICK_COLOR_2';


//board
export const SAVE_BOARD = 'SAVE_BOARD';
export const GET_USER_BOARDS = 'GET_USER_BOARDS';
export const UPDATE_CURRENT_BOARD = 'UPDATE_CURRENT_BOARD';
export const UPDATE_USER_BOARDS = 'UPDATE_USER_BOARDS';
export const DELETE_USER_BOARD = 'DELETE_USER_BOARD';
export const LOAD_CANVASES = 'LOAD_USER_BOARD';
export const CHANGE_BOARD_TITLE = 'CHANGE_BOARD_TITLE';
export const CLEAR_BOARD = 'CLEAR_BOARD';
export const CLEAR_CURRENT_BOARD = 'CLEAR_CURRENT_BOARD';


//alerts

export const UPDATE_ALERT = 'OPEN_ALERT';
export const CLOSE_ALERT = 'CLOSE_ALERT';



//canvas

export const SELECT_CANVAS = 'SELECT_CANVAS';
export const BACKGROUND_COLOR = 'ACTIONS/BACKGROUND_COLOR';
// export const PICK_COLOR_1 = 'PICK_COLOR_1';
// export const PICK_COLOR_2 = 'PICK_COLOR_2';



// templates

export const SWITCH_TEMPLATE = 'SWITCH_TEMPLATE';