export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';

//USER ACTIONS

export const CHECK_LOGGED_IN_STATUS = 'CHECK_LOGGED_IN_STATUS';
export const LOG_IN_USER = 'LOG_IN_USER';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const UPDATE_USER_STATUS = 'UPDATE_USER_STATUS'
export const PENDING_USER_LOGIN = 'PENDING_USER_LOGIN'
export const ERROR_LOGGING_IN = 'ERROR_LOGGING_IN'
export const REGISTER_USER = 'REGISTER_USER'
export const REGISTERING_USER = 'REGISTERING_USER'
export const ERROR_REGISTERING_USER = 'ERROR_REGISTERING_USER'
export const GET_CURRENT_USER = 'GET_CURRENT_USER'
export const SUCCESSFUL_GET_USER = 'SUCCESSFUL_GET_USER'
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA'



//full screen dialog

export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';
